---

- name: Configure {{bsd_named_conf_file}}
  lineinfile: >
    dest="{{bsd_named_conf_file}}"
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    backup="yes"
  with_items: "{{bsd_named_conf_lines}}"
  notify: reload named
  tags: freebsd_dns_config_named_conf

- name: Configure DNSSEC options in {{bsd_named_conf_file}}
  lineinfile: >
    dest="{{bsd_named_conf_file}}"
    insertafter="^options "
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    backup="yes"
  with_items:
    - { regexp: "dnssec-enable ", line: "\t dnssec-enable \t yes;" }
    - { regexp: "dnssec-validation ", line: "\t dnssec-validation \t yes;" }
  notify: reload named
  tags: freebsd_dns_config_named_conf_dnssec

- name: Configure zones in {{bsd_named_conf_file}}
  blockinfile:
    dest: "{{bsd_named_conf_file}}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK {{item.zone}}"
    insertafter: "EOF"
    owner: "root"
    group: "wheel"
    mode: "0644"
    backup: "yes"
    block: |
      zone "{{item.zone}}" {
              type {{item.type}};
              key-directory "{{bsd_named_conf_path}}/keys";
              update-policy local;
              auto-dnssec maintain;
              file "{{bsd_named_conf_path}}/{{item.type}}/{{item.zone}}";
      };
  with_items: "{{bsd_named_conf_zone}}"
  notify: reload named
  tags: freebsd_dns_config_zone

- name: Configure reverse zones in {{bsd_named_conf_file}}
  blockinfile:
    dest: "{{bsd_named_conf_file}}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK {{item.in}}"
    insertafter: "EOF"
    owner: "root"
    group: "wheel"
    mode: "0644"
    backup: "yes"
    block: |
      zone "{{item.in}}.IN-ADDR.ARPA" {
              type {{item.type}};
              file "{{bsd_named_conf_path}}/{{item.type}}/{{item.in}}.IN-ADDR.ARPA";
      };
  with_items: "{{bsd_named_conf_zone}}"
  when: item.reverse == "yes"
  notify: reload named
  tags: freebsd_dns_config_zone_rev

- name: Create zone files 
  template: >
    src="zone.j2"
    dest="{{bsd_named_conf_path}}/{{item.type}}/{{item.zone}}"
    owner="root"
    group="wheel"
    mode="0644"
    backup="yes"
  with_items: "{{bsd_named_conf_zone}}"
  notify: reload named
  tags: freebsd_dns_config_zone

- name: Create reverse zone files 
  template: >
    src="zone-in.j2"
    dest="{{bsd_named_conf_path}}/{{item.type}}/{{item.in}}.IN-ADDR.ARPA"
    owner="root"
    group="wheel"
    mode="0644"
    backup="yes"
  with_items: "{{bsd_named_conf_zone}}"
  when: item.reverse == "yes"
  notify: reload named
  tags: freebsd_dns_config_zone_rev

# EOF
