---

- name: Configure {{bsd_named_conf_file}}
  lineinfile: >
    dest="{{bsd_named_conf_file}}"
    insertafter="^options "
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    backup="yes"
  with_items: "{{bsd_named_conf_options}}"
  notify: restart named
  tags: bsd_dns_config_named_conf

- name: Configure DNSSEC options in {{bsd_named_conf_file}}
  lineinfile: >
    dest="{{bsd_named_conf_file}}"
    insertafter="^options "
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    backup="yes"
  with_items:
    - { regexp: "^\tdnssec-enable", line: "\tdnssec-enable\t{{bsd_named_conf_dnssec_enable}};" }
    - { regexp: "^\tdnssec-validation", line: "\tdnssec-validation\t{{bsd_named_conf_dnssec_validation}};" }
  notify: reload named
  tags: bsd_dns_config_named_conf_dnssec

- name: Configure zones in {{bsd_named_conf_file}}
  blockinfile:
    dest: "{{bsd_named_conf_file}}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK {{item.zone}}"
    insertafter: "EOF"
    owner: "root"
    group: "wheel"
    mode: "0644"
    backup: "yes"
    block: |
      zone "{{item.zone}}" {
              type {{item.type}};
              key-directory "{{bsd_named_conf_keys}}";
              update-policy local;
              auto-dnssec maintain;
              file "{{bsd_named_conf_path}}/{{item.type}}/{{item.zone}}.signed";
      };
  with_items: "{{bsd_named_conf_zone}}"
  notify: reload named
  tags: bsd_dns_config_zone

- name: Configure reverse zones in {{bsd_named_conf_file}}
  blockinfile:
    dest: "{{bsd_named_conf_file}}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK {{item.in}}"
    insertafter: "EOF"
    owner: "root"
    group: "wheel"
    mode: "0644"
    backup: "yes"
    block: |
      zone "{{item.in}}.IN-ADDR.ARPA" {
              type {{item.type}};
              file "{{bsd_named_conf_path}}/{{item.type}}/{{item.in}}.IN-ADDR.ARPA";
      };
  with_items: "{{bsd_named_conf_zone}}"
  when: item.reverse == "yes"
  notify: reload named
  tags: bsd_dns_config_zone_in

- name: Create zone files 
  template: >
    src="zone.j2"
    dest="{{bsd_named_conf_path}}/{{item.type}}/{{item.zone}}"
    owner="root"
    group="wheel"
    mode="0644"
    backup="yes"
  register: bsd_named_zones_created
  with_items: "{{bsd_named_conf_zone}}"
  notify:
    - reload named
# TODO: ERROR! 'dict object' has no attribute 'zone'
#    - sign zones
  tags: bsd_dns_config_zone

- name: Create reverse zone files 
  template: >
    src="zone-in.j2"
    dest="{{bsd_named_conf_path}}/{{item.type}}/{{item.in}}.IN-ADDR.ARPA"
    owner="root"
    group="wheel"
    mode="0644"
    backup="yes"
  with_items: "{{bsd_named_conf_zone}}"
  when: item.reverse == "yes"
  notify: reload named
  tags: freebsd_dns_config_zone_in

# EOF
