---

- name: Configure {{ bsd_named_conf_file }}
  lineinfile: >
    dest="{{ bsd_named_conf_file }}"
    insertafter="^options "
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backup="yes"
  with_items: "{{ bsd_named_conf_options }}"
  notify: restart named
  tags: bsd_dns_named_conf

- name: Configure default allow-transfer {{ bsd_named_conf_allow_transfer_default }} in {{ bsd_named_conf_file }}
  lineinfile: >
    dest="{{ bsd_named_conf_file }}"
    insertafter="^options "
    regexp="^\tallow-transfer\t{"
    line="\tallow-transfer\t{ {{ bsd_named_conf_allow_transfer_default }} };"
    backup="yes"
  when: bsd_named_conf_allow_transfer_default|length > 0
  notify: reload named
  tags: bsd_dns_named_conf_allow_transfer_default

- name: Configure forwarders {{ bsd_named_conf_forwarders }} in {{ bsd_named_conf_file }}
  lineinfile: >
    dest="{{ bsd_named_conf_file }}"
    insertafter="^options "
    regexp="^\tforwarders\t{"
    line="\tforwarders\t{ {{ bsd_named_conf_forwarders }} };"
    backup="yes"
  when: bsd_named_conf_forwarders|length > 0
  notify: reload named
  tags: bsd_dns_named_conf_forwarders

- name: Configure DNSSEC options in {{ bsd_named_conf_file }}
  lineinfile: >
    dest="{{ bsd_named_conf_file }}"
    insertafter="^options "
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backup="yes"
  with_items:
    - { regexp: "^\tdnssec-enable", line: "\tdnssec-enable\t{{ bsd_named_conf_dnssec_enable }};" }
    - { regexp: "^\tdnssec-validation", line: "\tdnssec-validation\t{{ bsd_named_conf_dnssec_validation }};" }
    - { regexp: "^\tdnssec-lookaside", line: "\tdnssec-lookaside\t{{ bsd_named_conf_dnssec_lookaside }};" }
  notify: reload named
  tags: bsd_dns_named_conf_dnssec

- name: Configure logging in {{ bsd_named_conf_file }}
  blockinfile:
    dest: "{{ bsd_named_conf_file }}"
    marker: "// {mark} ANSIBLE MANAGED BLOCK logging"
    insertafter: "EOF"
    backup: "yes"
    block: |
      logging {
        channel named_log {
          file "{{ bsd_named_conf_log_file }}" versions {{ bsd_named_conf_log_file_versions }} size {{ bsd_named_conf_log_file_size }};
          severity {{ bsd_named_conf_log_severity }};
          print-severity {{ bsd_named_conf_log_print_severity }};
          print-time {{ bsd_named_conf_log_print_time }};
          print-category {{ bsd_named_conf_log_print_category }};
        };
        category default {
          named_log;
        };
        category lame-servers {
          null;
        };
      };
  notify: reload named
  tags: bsd_dns_config_log
  
# EOF
...
