---
# tasks freebsd-dns

- include: packages.yml
  tags:
    - bsd_packages
    - bsd_ports
    - bsd_dns_all

- include: create_dirs.yml
  tags:
    - bsd_create_dirs
    - bsd_dns_all

- include: config_rc_conf.yml
  tags:
    - bsd_rc_conf
    - bsd_dns_all

- include: config_named.yml
  tags:
    - bsd_config_named
    - bsd_dns_all

- include: config_named_zones.yml
  tags:
    - bsd_config_named_zones
    - bsd_dns_all

# EOF
...
