---
# tasks vbotka.freebsd-dns

- import_tasks: debug.yml
  when: bsd_dns_debug
  tags: bsd_dns_debug

- import_tasks: packages.yml
  tags: bsd_dns_packages

- import_tasks: dirs.yml
  tags: bsd_dns_dirs

- import_tasks: named.yml
  tags: bsd_dns_named

- import_tasks: named_zones.yml
  tags: bsd_dns_named_zones

- import_tasks: rcconf.yml
  tags: bsd_dns_rcconf

# EOF
...
