---

- name: "named: Remove {{ bsd_named_conf_file }}"
  when: bsd_named_conf_recreate|bool
  file:
    path: "{{ bsd_named_conf_file }}"
    state: absent
  tags: bsd_named_conf

- name: "named: Stat {{ bsd_named_conf_file }}"
  stat:
    path: "{{ bsd_named_conf_file }}"
  register: conf_file
  tags: bsd_named_conf

- name: "named: Create {{ bsd_named_conf_file }}"
  when: not conf_file.stat.exists
  block:
    - name: "named: Create {{ bsd_named_conf_file }}"
      command: "cp {{ bsd_named_conf_file }}.sample {{ bsd_named_conf_file }}"
      args:
        creates: "{{ bsd_named_conf_file }}"
    - name: "named: Create BEGIN BLOCK options marker in {{ bsd_named_conf_file }}"
      when: not ansible_check_mode
      lineinfile:
        path: "{{ bsd_named_conf_file }}"
        insertbefore: "^options {"
        firstmatch: yes
        line: "// *** BEGIN ANSIBLE MANAGED BLOCK options ***"
    - name: "named: Create END BLOCK options marker in {{ bsd_named_conf_file }}"
      when: not ansible_check_mode
      lineinfile:
        path: "{{ bsd_named_conf_file }}"
        insertafter: "^};"
        firstmatch: yes
        line: "// *** END ANSIBLE MANAGED BLOCK options ***"
  tags: bsd_named_conf

- name: "named: Stat {{ bsd_named_conf_file }}"
  stat:
    path: "{{ bsd_named_conf_file }}"
  register: conf_file
  tags: bsd_named_conf

- name: "named: Fail when {{ bsd_named_conf_file }} is missing"
  when: not conf_file.stat.exists
  fail:
    msg: "[ERROR] {{ bsd_named_conf_file }} is missing. End of play."
  tags: bsd_named_conf

- name: "named: Configure options in {{ bsd_named_conf_file }}"
  blockinfile:
    dest: "{{ bsd_named_conf_file }}"
    marker: "// *** {mark} ANSIBLE MANAGED BLOCK options ***"
    block: "{{ lookup('template', 'block-named-options.j2') }}"
    validate: "named-checkconf %s"
    backup: "{{ bsd_named_backup_conf }}"
  notify: reload named
  tags: bsd_named_conf_options

- name: "named: Configure logging in {{ bsd_named_conf_file }}"
  when: bsd_named_conf_log|bool
  blockinfile:
    dest: "{{ bsd_named_conf_file }}"
    marker: "// *** {mark} ANSIBLE MANAGED BLOCK logging ***"
    insertafter: "EOF"
    block: "{{ lookup('template', 'block-named-logging.j2') }}"
    validate: "named-checkconf %s"
    backup: "{{ bsd_named_backup_conf }}"
  notify: reload named
  tags: bsd_named_conf_logging

# EOF
...
