---

- name: "package: Install dns packages"
  pkgng:
    name: "{{ item }}"
  with_items: "{{ bsd_dns_packages }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install dns ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  with_items: "{{ bsd_dns_packages }}"
  when: freebsd_install_method == "ports"

# EOF
...
