---

- name: "package: Install DNS packages."
  pkgng:
    name: "{{ bsd_dns_packages }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install DNS ports."
  portinstall:
    name: "{{ bsd_dns_packages }}"
    use_packages: "{{ freebsd_use_packages }}"
  when: freebsd_install_method == "ports"

# EOF
...
