---

- name: "package: Install DNS packages."
  when: freebsd_install_method == "packages"
  pkgng:
    name: "{{ bsd_dns_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"

- name: "packages: Install DNS ports."
  when: freebsd_install_method == "ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_dns_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"

# EOF
...
