---

- name: "zones: Stat {{ bsd_named_conf_file }}"
  stat:
    path: "{{ bsd_named_conf_file }}"
  register: conf_file

- name: "zones: Fail whem {{ bsd_named_conf_file }} is missing"
  when: not conf_file.stat.exists
  fail:
    msg: "[ERROR] {{ bsd_named_conf_file }} is missing. End of play."

- name: "zones: Set signed zone files for DNSSEC"
  when: bsd_named_conf_dnssec_enable == "yes"
  set_fact:
    bsd_named_zone_signed: ".signed"

- name: "zones: Configure master zones in {{ bsd_named_conf_file }}"
  when: item.type == "master"
  include_tasks: fn/conf_master_zone.yml
  loop: "{{ bsd_named_conf_zone }}"

- name: "zones: Configure slave zones in {{ bsd_named_conf_file }}"
  when: item.type == "slave"
  include_tasks: fn/conf_slave_zone.yml
  loop: "{{ bsd_named_conf_zone }}"

- name: "zones: Configure master reverse zones in {{ bsd_named_conf_file }}"
  when: item.type == "master" and item.reverse == "yes"
  include_tasks: fn/conf_master_zone_reverse.yml
  loop: "{{ bsd_named_conf_zone }}"

- name: "zones: Configure slave reverse zones in {{ bsd_named_conf_file }}"
  when: item.type == "slave" and item.reverse == "yes"
  include_tasks: fn/conf_slave_zone_reverse.yml
  loop: "{{ bsd_named_conf_zone }}"

- name: "zones: Create zone files"
  when: item.type == "master"
  include_tasks: fn/create_zone_file.yml
  loop: "{{ bsd_named_conf_zone }}"

- name: "zones: Create reverse zone files"
  when: item.type == "master" and item.reverse == "yes"
  include_tasks: fn/create_zone_reverse_file.yml
  loop: "{{ bsd_named_conf_zone }}"

# EOF
...
