---
# handlers freebsd-dns

- name: enable and start named
  service: >
    name="{{bsd_named_service}}"
    state="started"
    enabled="yes"

- name: disable and stop named
  service: >
    name="{{bsd_named_service}}"
    state="stopped"
    enabled="no"

- name: start named
  service: >
    name="{{bsd_named_service}}"
    state="started"

- name: stop named
  service: >
    name="{{bsd_named_service}}"
    state="stopped"

- name: restart named
  service: >
    name="{{bsd_named_service}}"
    state="restarted"

- name: reload named
  service: >
    name="{{bsd_named_service}}"
    state="reloaded"

# EOF
